name: Deploy to Netlify

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: netlify deploy --dir=build --prod
        env:
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_NAME }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - name: Create build tarball
        run: tar -zcvf new-year-countdown.tar.gz build 
      - uses: actions/upload-artifact@v2
        with:
          name: Built app
          path: new-year-countdown.tar.gz