name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build app
    runs-on: ubuntu-20.04
    steps:
      - name: Get source code
        uses: actions/checkout@v2
      - name: Install Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload built app
        uses: actions/upload-artifact@v2
        with:
          name: Built app
          path: build
      
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-20.04
    needs: build
    defaults:
      run:
        shell: bash
    environment:
      name: Vercel
      url: https://new-year-countdown-nine.vercel.app/
    steps:
      - name: Download built app
        uses: actions/download-artifact@v2
        with:
          name: Built app
          path: build
      - name: Add README
        run: curl -s https://raw.githubusercontent.com/$GITHUB_REPOSITORY/${GITHUB_REF#refs/heads/}/ci/static-build-README.md > README
      - name: Create .vercel/project.json
        run: |
          mkdir .vercel
          echo $VERCEL_PROJECT_JSON > .vercel/project.json
        env:
          VERCEL_PROJECT_JSON: ${{ secrets.VERCEL_PROJECT_JSON }}
      - name: Update Vercel CLI
        run: sudo npm install -g vercel@latest
      - name: Deploy🚀
        run: vercel --token $VERCEL_TOKEN --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  stable_merge:
    name: Merge main into stable
    needs: build
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Merge main into stable
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/merges \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "base": "main",
            "head": "head"
            }' \
          --fail
