name: Deploy to Netlify

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
            publish-dir: './build'
            production-branch: main
            deploy-message: '${{ github.event.head_commit.message }}'
        env:
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_NAME }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - name: Create build tarball
        run: tar -zcvf new-year-countdown.tar.gz build
      - uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_NAME }}
          build-dir: './build'
          draft: false